# Generated by Django 5.1.3 on 2024-12-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
